### ISSUE TITLE
idea: use sparse binomial matrix in HybridVSS 

### ISSUE THREAD

**Issue by ggkitsas** [heliaxdev/ferveo#4]
Early idea for discussion.

For:
* t-limited byzantine adversary
* $\phi(x,y) = XAY$, $X$ vector of powers of $x$, $Y$ vector of powers of $y$, $A$ is the $(t+1) \times (t+1)$ binomial matrix
* univariate polynomials generated by fixing the value of $x$ ($\phi(i,y)$)

We could reduce the amount of operations in `verify-poly` and `verify-point` by generating a sparse matrix for the binomial's coefficients. E.g. a O(tlogt) dense matrix will reduce both `verify-poly` and `verify-point` to O(tlogt) exponentiations and O(tlogt) multiplications.

Additionally, we could use compression for the commitment. If we consider commitment compression, we need to be careful since it leaks information on which are the zero factors. Some initial thoughts on what to be careful about:
*  last column of $A$ needs to have only non-zero coefficients, otherwise the secret will be recoverable by $t+1-k$  univariate polynomials, where $k$ the number of factors set to zero in last column
* $A_{0,0} \ne 0$ to maintain the degree of the binomial at $2t$ and of the univariates' at $t$

**Comment by joebebel** [comment]
It's an interesting idea. My first impression is that the asymptotics aren't very favorable - basically as the sparsity increases, the space of potential polynomials goes down by a factor of q (order of field) and up by a factor of at most t. So quickly there is probably enough information to recover the polynomials with only t shares. There might be a computational assumption that it's hard to recover, but I would guess not (it's the kind of problem that seems efficiently solvable even if not immediately obvious)

Plus, I'm not sure it saves that much. It saves multiplies in `verify-poly` but `verify-point` needs to know the monomial for each coefficient (and then it is efficiently interpolatable). If it uses KZG commitments, sparsity would save compute time for the dealer (though not for the verifier)
